### PR TITLE
Make compatible with python 3

### PR DESCRIPTION
**Pull request by w-**
#155

### CODE REVIEW

**Comment by timotheus** [comment]
Thanks for the contribution. Apologies for the delay.

**Comment by w-** [comment]
sweet. thx.  any idea on when you will be creating a new release?

**Comment by timotheus** [comment]
I’ll package and upload it tomorrow after I pull in one or two more fixes.

Tim

**Comment by timotheus** [comment]
I need to rollback this change. It's breaking existing code.

https://github.com/timotheus/ebaysdk-python/blob/master/samples/finding.py#L69

**Pull request merged**
