### PR TITLE
Allow dict2xml to construct xml from response dict

### PR DESCRIPTION
**Pull request by jmsfwk**
When `Response.dict()` converts `<element foo="bar">baz</element>` it returns a dictionary in the form:

``` python
...
    "element" : {
        "value" : "baz",
        "_foo" : "bar",
    }
...
```

`dict2xml` could convert a dictionary like:

``` python
{"element" : {
        "#text" : "baz",
        {
            "@attrs" : {
                "foo" : "bar",
            },
        },
    },
}
```

to `<element foo="bar">baz</element>`. The problem is that it makes it difficult to reuse parts of a response in a new request.

`dixt2xml` will now be able to construct an XML string using the `response`style dictionary.

### CODE REVIEW

**Comment by timotheus** [comment]
I definitely like this. My only concern is that it'll break backward compatibility for existing users. I'll have to think about how to best handle this change.

**Comment by listingmirror** [comment]
I think this wouldn't be bad as a flag.. but not something I would want to use.

My biggest complaint about the API is how arrays are returned as a not-array if a single element. Causes a bunch of checks "Is this a list of ITEM or a single ITEM", which is very annoying but not related to this ticket ;)

**Comment by timotheus** [comment]
Can you give me an example where it's not forcing the correct data type on
a given node? This should have been covered in prior updates. It's possible
I overlooked something.

**Comment by listingmirror** [comment]
@timotheus me specifically I was referring to how for almost anything, the data returned is either X or Array[X], which is weird.  For example:

GetCategorySpecifics.Recommendations
GetCategorySpecifics.Recommendations.NameRecommendation
GetSellerList.ItemArray.Item
GetSellerList.ItemArray.Item.Variations.Variation


It's not hard to "deal" with, I just wrap all my access in something silly like:
```

def listify(maybe_list):
    if maybe_list is None:
        return []
    elif isinstance(maybe_list, list):
        return maybe_list
    else:
        return [maybe_list]

```

But that isn't a very pythonic way to deal with arrays.

On the inbound way it all works good. can send an array of 1 item and it translates write.. but parsing out is yuck

**Pull request closed without merging**
